### ISSUE TITLE
a的设置以及dI的公式求解

### ISSUE THREAD

**Issue by zzheudora** [bigscity/metapopulation-SIR#1]
您好，我仔细的研究了您的代码，我有一些疑惑。在原论文中如果只看种群自身的话dI应该=alpha*s[j,i]*I[j,i]*q1，为什么您的代码要除以N[j]呢？`dI = a*S[j,i]*(q1*I[j,i] + q2*M)/N[j]`（这是种群自身和种群间作用共同作用的人口数的公式，但是内外部却都除以了Nj）
还有就是代码中a也就是论文中alpha的设置是怎么确定的呢？

非常期待您的回复。

**Comment by bigscity** [comment]
你好，这份代码并不是完全按照论文里的写法实现的，因此可能跟论文里有些差异。除以N[j]相当于做了一个归一化，有一部分SIR模型是有除以总人口的，这个跟alpha的设置有关。
按照论文里的做法，alpha应该是首先有一个初始值（通常是通过trial-and-error调试得到的），之后是通过NETWORK INFERENCE MODEL，结合交通数据使用梯度下降方法进行优化，参考eq.(6)的定义，alpha此时已经在网络G里了。

**Comment by zzheudora** [comment]
非常感谢您的回复，不知道能否有幸加一下您的联系方式，我的微信是1134322759，非常期待在将来有关于这方面不懂得知识能和您请教。
