### ISSUE TITLE
transition的数据指的是什么，ID_net[(i, j)] 为什么要除以20

### ISSUE THREAD

**Issue by zzheudora** [bigscity/metapopulation-SIR#2]
这个transition的数据是指两个国家的转移人口吗？这个数据是以什么为基准的呢？`ID_net_full[(i, j)] = ID_net[(i, j)] / 20.`又为什么要除以20呢？整个程序代码都非常清晰，只有这几个点我不太明白，非常期待您的讲解。另：可以加您的联系方式吗？非常想进一步学习和请教。

**Comment by bigscity** [comment]
这个transition的数据是指两个国家的转移人口吗？是的。
这个数据是以什么为基准的呢？国家间一般可以用航空数据，如果是paper里做城市级的话是用的出租车数据或者交通数据。
ID_net_full[(i, j)] = ID_net[(i, j)] / 20.又为什么要除以20呢？这个可以理解为做了个归一化，可能是这样做效果好一些。

**Comment by zzheudora** [comment]
非常感谢您的回复，同时非常期待您对于代码中dI的计算方法的解答。
